import { PRESERVED_FOLDERS } from "../constants/preservedFolders";

export type FolderType = 'system' | 'user';
export type RepetitionType = 'daily' | 'weekly'
// TODO: just a placeholder for now, implement all the types later
//export type RepetitionType = 'daily' | 'weekly' | 'bi-weekly' | 'monthly' | 'nth-day' | 'day-of-week' | 'day-of-month' | 'nth-time-of-day' | 'nth-time-of-week' | 'nth-time-of-month';
export type PreservedFolderType = typeof PRESERVED_FOLDERS[number];

export interface Folder {
    id: string;
    name: string;
    type: FolderType;
    createdAt: string;
}

export interface Activity {
    id: string;
    name: string;
    folder: string;
    repetitionType: RepetitionType;
    createdAt: string;
    deletedAt?: string | null;
}

export interface ActivityHistory {
    id: string;
    activityId: string;
    targetDate: string;
    storedAt: string;
    isDone: boolean;
    isAutoGenerated: boolean;
}
